name: KalkukatorDBD
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  toggle_switch: ^2.0.1  
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  smart_select: ^4.3.2
  parent_child_checkbox: ^0.0.3

dev_dependencies:

  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_logo"
  ios: true
  image_path: "assets/ic_logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/ic_logo.png"
    background_color: "
    theme_color: "
  windows:
    generate: true
    image_path: "path/ic_logo.png"
    icon_size: 48 

flutter:
  uses-material-design: true
  assets:
    - assets/
